<?php
return array(
    'RSA_PUB_KEY'=>'-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArl1nnslPhAnd9EkWdW2r
dREeD2Msa/fPFg0PRai7+UX0JgQQ0wnQD7d1otDDxA2oMxa4865cQKroccEwbmdy
pDg2VYGQXFFjnEisfmhXjUu9ELZb9grFiJRBy/fUHhJqxR7xCasmiIIXMV6O/08G
6pRyRJdJWuujxTwU3mnhuTeKIHLZtYWrH3XwYVAQW91ENhPpJg4srXvT/xAOs2DY
ZERwThxa6ZRuHW4zJbDGeDL4+Ho1otWpBHd8dqYeAUFUPcYu8Kyp47KKFBahiszC
+HGdZqLHhGLwpV6NJVIgek6weZbKFjCSY0RHghljggJDI1ORBaU7srWGHFSjnwyr
5QIDAQAB
-----END PUBLIC KEY-----',
);